task:
  name: windows
  windows_container:
    image: cirrusci/windowsservercore:cmake
    os_version: 2019
 # env:
 #   CIRRUS_SHELL: C:\msys64\usr\bin\bash
  test_script: echo "Hello World from Windows"
  setup_script:
    # - dir c:\msys64
    - dir c:\tools
    - C:\tools\msys64\usr\bin\bash -lc 'cd "%cd%"; echo $PWD; make CC=gcc prep'
