#task:
#  name: linux
#  container:
#    image: ubuntu:latest
#  setup_script:
#    - apt-get update && apt-get install -y build-essential git make gcc pkg-config libudev-dev
#    - git fetch --tags origin
#  build_script:
#    - make
#  test_script:
#    - ./testme
#  artifacts:
#    path: testme

#task:
#  name: macosx
#  osx_instance:
#    image: mojave-xcode
#  setup_script:
#    - git fetch --tags origin
#  build_script:
#    - make
#  test_script:
#    - ./testme
#  artifacts:
#    path: testme

task:
  name: windows
  windows_container:
    image: cirrusci/windowsservercore:2019
    os_version: 2019
  setup_script:
    - git fetch --tags origin
#    - git tag
  build_script:
    - echo %PATH%
    - set PATH=C:\tools\msys64\usr\bin;c:\tools\msys64\mingw64\bin;%PATH%;
    - dir "C:\Program Files\"
    - dir "C:\Program Files (x86)\"
    - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
    - mingw32-make
    - lib /?
  test_script:
    - testme.exe
  artifacts:
    path: testme.exe

#### no no no no no

#    - which gcc
    #- pacman -S --noconfirm base-devel make git zip unzip
    #- pacman -S --noconfirm mingw-w64-x86_64-toolchain
    #- pacman -S --noconfirm make zip

  #  - choco install mingw
    # - dir c:\
    # - dir c:\ProgramData\chocolatey\bin
    # - dir c:\tools\msys64
    # - dir c:\tools\msys64\usr\bin
    # - dir c:\tools\msys64\clang64
    # - dir c:\tools\msys64\clang64\bin
    # - dir c:\tools\msys64\mingw64\
    # - dir c:\tools\msys64\mingw64\bin
  #  - C:\tools\msys64\usr\bin\bash -lc 'cd "%cd%"; echo $PWD; make'
