task:
  name: windows
  windows_container:
    image: cirrusci/windowsservercore:cmake
    os_version: 2019
  test_script: echo "Hello World from Windows"
  setup_script:
  #  - choco install mingw
    - dir c:\
    - dir c:\tools
    - dir c:\tools\msys64
    - dir c:\tools\msys64\usr\bin
    - dir c:\tools\msys64\clang64
    - dir c:\tools\msys64\clang64\bin
    - dir c:\tools\msys64\mingw64\
    - dir c:\tools\msys64\mingw64\bin
    - C:\tools\msys64\usr\bin\bash -lc 'cd "%cd%"; echo $PWD; make CC=gcc'
