# This is a basic workflow to help you get started with Actions

name: macos

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: check xcode version
        shell: bash
        run: xcodebuild -version

      - name: ls Applications
        shell: bash
        run: ls -al /Applications

      - name: list homeberw
        shell: bash
        run: brew list

      # - name: update xcode w/ arm
      #   shell: bash
      #   run: |
      #     sudo rm -Rf /Library/Developer/CommandLineTools/SDKs/*
      #     sudo xcode-select -s "/Applications/Xcode_13.2.app"
      # #     sudo xcode-select -s "/Applications/Xcode_12.4.app"

      - name: compile
        shell: bash
        run: make

      - name: run app
        shell: bash
        run: |
          file ./testme
          ./testme

      - name: Checkout blink1-tool
        #if: steps.cache.outputs.cache-hit != 'true'
        run: git clone https://github.com/todbot/blink1-tool

      - name: Compile blink1-tool
        shell: bash
        run: cd blink1-tool && make

      # - name: Compile blink1control-tool
      #   shell: bash
      #   run: cd blink1-tool && make blink1control-tool

      - name: Compile blink1control-tool by hand
        shell: bash
        run: |
          cd blink1control-tool
          ls -al
          make curl-setup
          ls -al
          ls -al curl-macosx/*
          make
