
name: linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: setup prerequisites (linux)
      run: |
        sudo apt update 
        sudo apt install pkg-config libudev-dev libusb-1.0-0-dev
        which clang-9
        echo "CC=clang-9" >> $GITHUB_ENV
        echo "CXX=clang++-9" >> $GITHUB_ENV
        # however this export does not work
        export CC=clang-9
        export CXX=clang++-9 
  
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: |
        git clone https://github.com/node-hid/node-hid
        cd node-hid
        npm run prepublishOnly
        npm install --build-from-source
        npm test
        npm run prebuild
        env 

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: prebuild-linux
        path: node-hid/prebuilds/*tar.gz
